### ISSUE TITLE
OOM error (Resource Exhausted when trying to run on TensorFlow GPU)

### ISSUE THREAD

**Issue by kandilidinesh** [xavysp/DexiNed#13]
`ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,16,280,480] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc`

I am getting this error when I try to run the DexiNED model on Tensorflow GPU 1.13.1 with a Batch Size of 8, 4 and 1 also.

**System Configuration:**

- OS: Ubuntu 18.04
- Python: 3.7.3
- Tensorflow GPU: 1.13.1
- CUDA: 10.0
- GPU: NVIDIA Geforce GTX 1080 (8 GB RAM)
- RAM: 64 GB RAM

@xavysp Help me out on this, sir.

**Comment by kandilidinesh** [comment]
**Error Resolved:**

I changed the batch size from 8 to 4 since my GPU has 8GB RAM. Now, training is happening.
